#include "MobileSurfaceNavComponent.h"

#include "MobileSurfaceNavAgent.h"
#include "MobileSurfaceNavSubsystem.h"
#include "MobileSurfaceNavigationBuilder.h"
#include "MobileSurfaceNavigationDebug.h"
#include "MobileSurfaceNavigationQuery.h"
#include "MobileSurfacePathfinder.h"

#include "Components/SceneComponent.h"
#include "Components/StaticMeshComponent.h"
#include "DrawDebugHelpers.h"
#include "Engine/World.h"
#include "GameFramework/Actor.h"

UMobileSurfaceNavComponent::UMobileSurfaceNavComponent()
{
	PrimaryComponentTick.bCanEverTick = true;
	PrimaryComponentTick.bStartWithTickEnabled = false;
}

void UMobileSurfaceNavComponent::RebuildNavigationData()
{
	LastBuildError.Reset();
	NavigationData.Reset();
	bLastBuildSucceeded = false;

	FMobileSurfaceNavBuildSettings Settings;
	Settings.VertexWeldTolerance = VertexWeldTolerance;
	Settings.PlanarRegionAngleToleranceDegrees = PlanarRegionAngleToleranceDegrees;
	Settings.PlanarRegionDistanceTolerance = PlanarRegionDistanceTolerance;
	Settings.BoundarySimplificationTolerance = BoundarySimplificationTolerance;
	UStaticMeshComponent* SourceMeshComponent = GetNavigationSourceMeshComponent();
	USceneComponent* NavigationSpaceComponent = GetNavigationSpaceComponent();

	if (!FMobileSurfaceNavigationBuilder::BuildFromStaticMeshComponent(
		SourceMeshComponent,
		NavigationSpaceComponent,
		Settings,
		NavigationData,
		LastBuildError))
	{
		UpdateTickState();
		return;
	}

	bLastBuildSucceeded = true;

	UpdateTickState();

	if (bAutoDrawDebugAfterRebuild)
	{
		DrawNavigationDebug(DebugDuration);
	}
}

void UMobileSurfaceNavComponent::DrawNavigationDebug(const float Duration)
{
	FMobileSurfaceNavDebugSettings Settings;
	Settings.bDrawVertices = bDrawVertices;
	Settings.bDrawBoundaryEdges = bDrawBoundaryEdges;
	Settings.bDrawTriangles = bDrawTriangles;
	Settings.bDrawTriangleNormals = bDrawTriangleNormals;
	Settings.bDrawPortals = bDrawPortals;
	Settings.Duration = Duration;

	FMobileSurfaceNavigationDebug::DrawNavData(GetWorld(), GetNavigationSpaceComponent(), NavigationData, Settings);
	DrawDebugPath(Duration);
}

bool UMobileSurfaceNavComponent::FindPathLocal(const FVector& StartLocalPosition, const FVector& EndLocalPosition, FMobileSurfaceNavPath& OutPath, const float AgentRadius) const
{
	FMobileSurfacePathQueryParams Params;
	Params.AgentRadius = AgentRadius;
	return FMobileSurfacePathfinder::FindPath(NavigationData, StartLocalPosition, EndLocalPosition, Params, OutPath);
}

int32 UMobileSurfaceNavComponent::FindContainingTriangle(const FVector& LocalPosition) const
{
	return FMobileSurfaceNavigationQuery::FindContainingTriangle(NavigationData, LocalPosition);
}

int32 UMobileSurfaceNavComponent::FindNearestTriangle(const FVector& LocalPosition) const
{
	return FMobileSurfaceNavigationQuery::FindNearestTriangle(NavigationData, LocalPosition);
}

void UMobileSurfaceNavComponent::ClearNavigationData()
{
	NavigationData.Reset();
	LastBuildError.Reset();
	bLastBuildSucceeded = false;
	UpdateTickState();
}

bool UMobileSurfaceNavComponent::HasValidNavigationData() const
{
	return NavigationData.bIsValid;
}

bool UMobileSurfaceNavComponent::WasLastBuildSuccessful() const
{
	return bLastBuildSucceeded;
}

const FMobileSurfaceNavData& UMobileSurfaceNavComponent::GetNavigationData() const
{
	return NavigationData;
}

const FString& UMobileSurfaceNavComponent::GetLastBuildError() const
{
	return LastBuildError;
}

UStaticMeshComponent* UMobileSurfaceNavComponent::GetNavigationSourceMeshComponent() const
{
	if (AActor* Owner = GetOwner())
	{
		return Cast<UStaticMeshComponent>(NavigationSourceMesh.GetComponent(Owner));
	}

	return nullptr;
}

USceneComponent* UMobileSurfaceNavComponent::GetNavigationSpaceComponent() const
{
	if (AActor* Owner = GetOwner())
	{
		if (USceneComponent* RootComponent = Owner->GetRootComponent())
		{
			return RootComponent;
		}
	}

	return GetNavigationSourceMeshComponent();
}

void UMobileSurfaceNavComponent::BeginPlay()
{
	Super::BeginPlay();
	DebugPathRandomStream.Initialize(DebugPathRandomSeed);

	if (UWorld* World = GetWorld())
	{
		if (UMobileSurfaceNavSubsystem* Subsystem = World->GetSubsystem<UMobileSurfaceNavSubsystem>())
		{
			Subsystem->RegisterNavSurface(this);
		}
	}

	if (bRebuildOnBeginPlay && !NavigationData.bIsValid)
	{
		RebuildNavigationData();
	}

	if (bAutoGenerateDebugPaths)
	{
		GenerateDebugPath();
	}

	if (bSpawnDebugAgentsOnBeginPlay)
	{
		SpawnDebugAgents();
	}

	UpdateTickState();
}

void UMobileSurfaceNavComponent::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	if (UWorld* World = GetWorld())
	{
		if (UMobileSurfaceNavSubsystem* Subsystem = World->GetSubsystem<UMobileSurfaceNavSubsystem>())
		{
			Subsystem->UnregisterNavSurface(this);
		}
	}

	DestroyDebugAgents();
	Super::EndPlay(EndPlayReason);
}

void UMobileSurfaceNavComponent::TickComponent(
	float DeltaTime,
	enum ELevelTick TickType,
	FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	if (bDrawDebugEveryTick && NavigationData.bIsValid)
	{
		DrawNavigationDebug(0.0f);
	}

	if (bAutoGenerateDebugPaths && NavigationData.bIsValid)
	{
		DebugPathTimeAccumulator += DeltaTime;
		if (DebugPathTimeAccumulator >= DebugPathGenerationInterval)
		{
			DebugPathTimeAccumulator = 0.0f;
			GenerateDebugPath();
		}

		DrawDebugPath(0.0f);
	}
}

#if WITH_EDITOR
void UMobileSurfaceNavComponent::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent)
{
	Super::PostEditChangeProperty(PropertyChangedEvent);

	const FName PropertyName = PropertyChangedEvent.GetPropertyName();
	if (PropertyName == GET_MEMBER_NAME_CHECKED(UMobileSurfaceNavComponent, NavigationSourceMesh))
	{
		NavigationData.Reset();
		LastBuildError.Reset();
		bLastBuildSucceeded = false;
	}

	UpdateTickState();
}
#endif

void UMobileSurfaceNavComponent::UpdateTickState()
{
	SetComponentTickEnabled((bDrawDebugEveryTick || bAutoGenerateDebugPaths) && NavigationData.bIsValid);
}

void UMobileSurfaceNavComponent::GenerateDebugPath()
{
	CurrentDebugPath = FMobileSurfaceNavPath();

	if (!NavigationData.bIsValid || NavigationData.Triangles.Num() < 2)
	{
		return;
	}

	const int32 StartTriangleIndex = DebugPathRandomStream.RandRange(0, NavigationData.Triangles.Num() - 1);
	int32 EndTriangleIndex = DebugPathRandomStream.RandRange(0, NavigationData.Triangles.Num() - 1);
	for (int32 AttemptIndex = 0; AttemptIndex < 8 && EndTriangleIndex == StartTriangleIndex; ++AttemptIndex)
	{
		EndTriangleIndex = DebugPathRandomStream.RandRange(0, NavigationData.Triangles.Num() - 1);
	}

	if (EndTriangleIndex == StartTriangleIndex)
	{
		return;
	}

	const FVector Start = NavigationData.Triangles[StartTriangleIndex].Center;
	const FVector End = NavigationData.Triangles[EndTriangleIndex].Center;
	FindPathLocal(Start, End, CurrentDebugPath);

	if (CurrentDebugPath.bIsValid)
	{
		DrawDebugPath(DebugPathDuration);
	}
}

void UMobileSurfaceNavComponent::DrawDebugPath(const float Duration) const
{
	if (!CurrentDebugPath.bIsValid || CurrentDebugPath.Waypoints.Num() < 2)
	{
		return;
	}

	UWorld* World = GetWorld();
	const USceneComponent* SpaceComponent = GetNavigationSpaceComponent();
	if (!World || !SpaceComponent)
	{
		return;
	}

	const FTransform LocalToWorld = SpaceComponent->GetComponentTransform();
	constexpr uint8 DepthPriority = 0;

	if (bDrawRawDebugPath && CurrentDebugPath.RawWaypoints.Num() >= 2)
	{
		for (int32 WaypointIndex = 0; WaypointIndex + 1 < CurrentDebugPath.RawWaypoints.Num(); ++WaypointIndex)
		{
			const FVector Start = LocalToWorld.TransformPosition(CurrentDebugPath.RawWaypoints[WaypointIndex]);
			const FVector End = LocalToWorld.TransformPosition(CurrentDebugPath.RawWaypoints[WaypointIndex + 1]);
			DrawDebugLine(World, Start, End, FColor::Orange, false, Duration, DepthPriority, 2.0f);
		}
	}

	for (int32 WaypointIndex = 0; WaypointIndex + 1 < CurrentDebugPath.Waypoints.Num(); ++WaypointIndex)
	{
		const FVector Start = LocalToWorld.TransformPosition(CurrentDebugPath.Waypoints[WaypointIndex]);
		const FVector End = LocalToWorld.TransformPosition(CurrentDebugPath.Waypoints[WaypointIndex + 1]);
		DrawDebugLine(World, Start, End, FColor::Red, false, Duration, DepthPriority, 6.0f);
		DrawDebugPoint(World, Start, 16.0f, WaypointIndex == 0 ? FColor::Green : FColor::Red, false, Duration, DepthPriority);
	}

	DrawDebugPoint(World, LocalToWorld.TransformPosition(CurrentDebugPath.Waypoints.Last()), 16.0f, FColor::Blue, false, Duration, DepthPriority);
}

void UMobileSurfaceNavComponent::SpawnDebugAgents()
{
	DestroyDebugAgents();

	if (!NavigationData.bIsValid || NavigationData.Triangles.IsEmpty())
	{
		return;
	}

	UWorld* World = GetWorld();
	USceneComponent* SpaceComponent = GetNavigationSpaceComponent();
	if (!World || !SpaceComponent)
	{
		return;
	}

	const TSubclassOf<AMobileSurfaceNavAgent> AgentClass = DebugAgentClass.Get() ? DebugAgentClass : TSubclassOf<AMobileSurfaceNavAgent>(AMobileSurfaceNavAgent::StaticClass());
	FRandomStream AgentRandom(DebugAgentRandomSeed);

	for (int32 AgentIndex = 0; AgentIndex < DebugAgentCount; ++AgentIndex)
	{
		FVector LocalSpawn = FVector::ZeroVector;
		bool bFoundSpawn = false;
		for (int32 AttemptIndex = 0; AttemptIndex < 16; ++AttemptIndex)
		{
			const int32 TriangleIndex = AgentRandom.RandRange(0, NavigationData.Triangles.Num() - 1);
			const FVector CandidateSpawn = NavigationData.Triangles[TriangleIndex].Center;
			FMobileSurfaceNavPath TestPath;
			if (FindPathLocal(CandidateSpawn, CandidateSpawn, TestPath, DebugAgentRadius))
			{
				LocalSpawn = CandidateSpawn;
				bFoundSpawn = true;
				break;
			}
		}

		if (!bFoundSpawn)
		{
			continue;
		}

		FActorSpawnParameters SpawnParameters;
		SpawnParameters.Owner = GetOwner();
		SpawnParameters.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;

		AMobileSurfaceNavAgent* Agent = World->SpawnActor<AMobileSurfaceNavAgent>(
			AgentClass,
			SpaceComponent->GetComponentTransform().TransformPosition(LocalSpawn),
			FRotator::ZeroRotator,
			SpawnParameters);

		if (!Agent)
		{
			continue;
		}

		Agent->InitializeAgent(this, DebugAgentRadius, DebugAgentMoveSpeed, DebugAgentRandomSeed + AgentIndex * 31);
		SpawnedDebugAgents.Add(Agent);
	}
}

void UMobileSurfaceNavComponent::DestroyDebugAgents()
{
	for (AMobileSurfaceNavAgent* Agent : SpawnedDebugAgents)
	{
		if (IsValid(Agent))
		{
			Agent->Destroy();
		}
	}

	SpawnedDebugAgents.Reset();
}
